services:
  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./PHP:/app/PHP
    container_name: go
    ports:
      - "8181:8181"
    restart: unless-stopped

  php-server:
    image: php:5.6-cli
    working_dir: /var/www/html
    stop_grace_period: 1s
    volumes:
      - ./PHP:/var/www/html
    command: php -S 0.0.0.0:8000 -t /var/www/html
    ports:
      - "8000:8000"
    restart: unless-stopped